### PR TITLE
Modify examples/extract.rs, reduce code.

### PR DESCRIPTION
**Pull request by biluohc**

### CODE REVIEW

**Comment by mvdnes** [comment]
Although I see some improvements, I am not really happy with the new output format. Could you maybe change those?
Something like `"File {} comment: {}"` and `"File {} extracted to \"{}\" ({} bytes)"` perhaps?

**Comment by biluohc** [comment]
Ok, I will modify the output format to your love.
But you use C's style to handle the Result, Maybe it is not beautiful? 
As follows:
```rust
fn main() {
    std::process::exit(real_main());
}

fn real_main() -> i32
{ 
many unwrap()
}
```

**Comment by biluohc** [comment]
I use `i` as the first argument, because of the output will very long and repeated if use `file.name()`.

```rust
          println!("File {} comment: {}", i, comment);
          println!("Dir {} extracted to \"{}\"", i, outpath.as_path().display());
          println!("File {} extracted to \"{}\" ({} bytes)", i, outpath.as_path().display(), file.size());
```

**Comment by biluohc** [comment]
Use `File` to replace `Dir` for aligning.
Comit ID: 09f728e
```rust
          println!("File {} comment: {}", i, comment);
          println!("File {} extracted to \"{}\"", i, outpath.as_path().display());
          println!("File {} extracted to \"{}\" ({} bytes)", i, outpath.as_path().display(), file.size());
```

**Comment by mvdnes** [comment]
Sorry for the late reaction. Thanks for the change! 👍

**Pull request merged**
